#!/bin/sh /etc/rc.common

START=10
USE_PROCD=1
PROG=/usr/bin/dnsproxy

start_service(){
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 0
	procd_close_instance
}
