#!/bin/sh

# When the ppp link comes up, this script is called with the following
# parameters
#       $1      the interface name used by pppd (e.g. ppp3)
#       $2      the tty device name
#       $3      the tty device speed
#       $4      the local IP address for the interface
#       $5      the remote IP address
#       $6      the parameter specified by the 'ipparam' option to pppd

jstr="{\"method\":\"set\",\"status\":\"Connected\",\"ifname\":\"$1\",\"localip\":\"$4\",\"remoteip\":\"$5\"}"
dbus-send --system --print-reply --dest=com.upointech.vpnclient1 /com/upointech/vpnclient1 com.upointech.vpnclient1.management.PostMsg string:$jstr