#!/bin/sh /etc/rc.common
# Copyright (C) 2013-2014 OpenWrt.org

START=20
USE_PROCD=1
PROG=/sbin/hpsrv

start_service(){
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 0
	procd_close_instance
}
