#! /bin/sh
LogToVdata
echo !reload > /proc/wap_proc/wap_log
echo !reload > /proc/wap_proc/wap_debug_log
echo !reload > /proc/wap_proc/flow_log
echo !reload > /proc/wap_proc/dhcpd_log
echo !head 0 > /proc/wap_proc/dhcpd_log
echo !reload > /proc/wap_proc/historyalm_log
echo !reload > /proc/wap_proc/pon_log
echo !reload > /proc/wap_proc/ap_log
echo !reload > /proc/wap_proc/alarm_log
echo !reload > /proc/wap_proc/alarm_wifi
echo !reload > /proc/wap_proc/alarm_net
echo !reload > /proc/wap_proc/alarm_comm
echo !reload > /proc/wap_proc/instrusion_log
echo !reload > /proc/wap_proc/voice_log
echo !reload > /proc/wap_proc/nff_log
